---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - '32181:32181'
    expose:
      - 32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BROKER_ID: 0
    hostname: kafka0
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper